# -*- coding: utf-8 -*-
"""Collab_Filtering_Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-R8dZTAFDEYpriVLVV_gUdQcYMyVcbpe
"""
import pandas as pd
from scipy.sparse import csr_matrix
from implicit import als
import numpy as np

restaurant_path = 'CA_Restaurants.csv'
review_path = 'CA_Reviews.csv'
user_path = 'CA_Users.csv'

restaurants = pd.read_csv(restaurant_path).iloc[:,1:]
reviews = pd.read_csv(review_path).iloc[:,1:]
users = pd.read_csv(user_path).iloc[:,1:]

def train_collab_filter(reviews_df, factors, regularization, iterations):
  review_matrix = reviews_df.pivot_table(index='user_id', columns='business_id', values='stars', aggfunc='first', fill_value=0)
  sparse_review_matrix = csr_matrix(review_matrix.values)
  #Train ALS model
  model = als.AlternatingLeastSquares(
      factors=factors,        # latent dimensions
      regularization=regularization,
      iterations=iterations,
      use_gpu=False
  )
  model.fit(sparse_review_matrix)

  return model

def predict_collab_filter(restaurant_df, model, reviews_df, N, user_idx):
  review_matrix = reviews_df.pivot_table(index='user_id', columns='business_id', values='stars', aggfunc='first', fill_value=0)
  sparse_review_matrix = csr_matrix(review_matrix.values)
  ids, scores = model.recommend(
      user_idx,
      sparse_review_matrix[user_idx],
      N=N                    # top N recommendations
  )

  # Map indices back to restaurant ids
  recommended = review_matrix.columns[ids]
  return restaurant_df[restaurant_df['business_id'].isin(list(recommended))]

my_model = train_collab_filter(reviews, 50, .1, 20)
print(predict_collab_filter(restaurants, my_model, reviews, 5, 15))

